//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYSDModelContainer : DbContext
    {
        public MYSDModelContainer()
            : base("name=MYSDModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VenueVendor> VenueVendors { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Hall> Halls { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<LoginActivity> LoginActivities { get; set; }
    }
}
