//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int Id { get; set; }
        public string DurationByHr { get; set; }
        public string Cost { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
